org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
loader_version=0.19.3
fabric_version=0.92.11+1.20.1

mod_id=portable_workstations
mod_name=HP's Portable Workstations
mod_version=1.1
mod_license=All Rights Reserved
mod_authors=hp
mod_description=Portable vanilla workstations controlled from a player skill wheel.
maven_group=com.portable_workstations
archives_base_name=portable_workstations
